/**:
  ros__parameters:
    problem:
      is_2d: true
      replanning_period: 0.06
      control_mode: 0 # 0: jerk input, 1: accel input, 2: velocity input
    obstacle_manager:
      planning_horizon: 1.0 # TODO: (1)
    target_manager:
      sampling:
        num_sample: 300
        num_thread: 4
        is_lite: false
      horizon:
        prediction: 1.0 # TODO: (2)
      dynamic_limits:
        vel_max: 1.0
        acc_max: 0.05
      distance:
        obstacle_max: 1.5
      virtual_pcl_bbox:
        width: 10.0
        height: 3.0
    trajectory_planner:
      sampling:
        num_sample: 500
        num_thread: 4
        is_lite: false
      horizon:
        planning: 1.0 #TODO: (3) -> (1)-(3) should be same
      distance:
        obstacle_max: 1.5
        end_points_min: 0.4
        end_points_max: 0.8
        target_min: 0.25
        target_max: 1.5
      dynamic_limits:
        vel_max: 5.0
        acc_max: 10.0
        yaw_rate_max: 5.0
      safe_distance:
        rx: 0.15
        ry: 0.15
        rz: 0.15
      virtual_pcl_bbox:
        width: 5.0
        height: 3.0

