/**:
  ros__parameters:
    problem:
      is_2d: false
      replanning_period: 0.08
    obstacle_manager:
      planning_horizon: 1.0 # TODO: (1)
    target_manager:
      sampling:
        num_sample: 300
        num_thread: 10
        is_lite: false
      horizon:
        prediction: 1.0 # TODO: (2)
      dynamic_limits:
        vel_max: 1.0
        acc_max: 0.05
      distance:
        obstacle_max: 2.0
      virtual_pcl_bbox:
        width: 10.0
        height: 3.0
    trajectory_planner:
      sampling:
        num_sample: 500
        num_thread: 10
        is_lite: false
      horizon:
        planning: 1.0 #TODO: (3) -> (1)-(3) should be same
      distance:
        obstacle_max: 3.0
        end_points_min: 0.6
        end_points_max: 0.8
        target_min: 0.4
        target_max: 1.0
      dynamic_limits:
        vel_max: 2.0
        acc_max: 10.0
        yaw_rate_max: 0.7
      safe_distance:
        rx: 0.05
        ry: 0.05
        rz: 0.05
      virtual_pcl_bbox:
        width: 5.0
        height: 3.0

