/**:
  ros__parameters:
    problem:
      is_2d: true
      replanning_period: 0.07
    obstacle_manager:
      planning_horizon: 1.0 # TODO: (1)
    target_manager:
      sampling:
        num_sample: 300
        num_thread: 6
        is_lite: false
      horizon:
        prediction: 1.0 # TODO: (2)
      dynamic_limits:
        vel_max: 1.0
        acc_max: 0.05
      distance:
        obstacle_max: 2.0
      virtual_pcl_bbox:
        width: 10.0
        height: 3.0
    trajectory_planner:
      sampling:
        num_sample: 250
        num_thread: 5
        is_lite: false
      horizon:
        planning: 1.0 #TODO: (3) -> (1)-(3) should be same
      distance:
        obstacle_max: 2.0
        end_points_min: 0.3
        end_points_max: 0.6
        target_min: 0.3
        target_max: 0.7
      dynamic_limits:
        vel_max: 2.0
        acc_max: 5.0
      safe_distance:
        rx: 0.01
        ry: 0.01
        rz: 0.00
      virtual_pcl_bbox:
        width: 5.0
        height: 3.0

