name: Ros build

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: foxy
      - name: build
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: los_keeper los_keeper_msgs los_keeper_ros2
          target-ros2-distro: foxy

  style:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: DoozyX/clang-format-lint-action@v0.16.1
        with:
          source: '.'
          extensions: 'cc,h'
          style: file
          clangFormatVersion: '10'
          check-path: '.'
